### ISSUE TITLE
where is `load_iwpc`

### ISSUE THREAD

**Issue by charlotte12l** [facebookresearch/fisher_information_loss#5]
Thank you for making your codes open source! I'm wondering where is `load_iwpc`? In Line 219 of `dataloading.py`, 
```
from main import load_iwpc
```

However there is no `main` or `load_iwpc` :(

**Comment by cg563** [comment]
We depend on the repo https://github.com/samuel-yeom/ml-privacy-csf18 for loading the IWPC dataset. If you install the [GitPython](https://gitpython.readthedocs.io/en/stable/intro.html) library, this repo should be automatically cloned when you run the code; see https://github.com/facebookresearch/fisher_information_loss/blob/main/dataloading.py#L215. 

Sorry for the confusion, and let me know if you have further questions.
