### ISSUE TITLE
Is `XTXdiag` used in LeastSquares?

### ISSUE THREAD

**Issue by charlotte12l** [facebookresearch/fisher_information_loss#6]
Sorry for bothering you again, we're studying your paper recently :)

In `class LeastSquares` `train`, I saw the variable `XTXdiag`
```
  XTXdiag = torch.diagonal(XTX)
  XTXdiag += (n * l2)
```

According to the paper, `XTXdiag` seems to be the Hessian, and will be used to calculate the Jacobian. However, in the codes, I didn't see anywhere using `XTXdiag`.  But if I change the value of `l2`(only `XTXdiag` uses `l2` ), the output results would change, which means there is somewhere using `XTXdiag`. Maybe calculating `XTXdiag` did influence `XTX` and thus influence `self.A`?  I'm really confused about that and I'd appreciate it if I can get some explanation :)

**Comment by cg563** [comment]
`torch.diagonal` creates a partial view (see https://pytorch.org/docs/stable/generated/torch.diagonal.html) of the underlying tensor `XTX`, so the subsequent line actually adds `n * l2` to the diagonal of `XTX`. Sorry for the confusion!
